import { UserRole, Permission } from '../../models/user.model';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  applicant: [
    'view_own_profile',
    'update_own_profile',
    'view_application_status',
  ],
  volunteer: [
    'view_home',
    'view_map',
    'view_tasks',
    'create_need',
    'update_own_task',
    'view_own_profile',
    'update_own_profile',
    'view_insights_own',
  ],
  field_lead: [
    'view_home',
    'view_map',
    'view_tasks',
    'create_need',
    'update_own_task',
    'update_team_task',
    'view_own_profile',
    'update_own_profile',
    'view_team_profiles',
    'view_insights_own',
    'view_insights_team',
    'request_inventory',
  ],
  ngo_admin: [
    'view_home',
    'view_map',
    'view_tasks',
    'create_task',
    'create_need',
    'assign_task',
    'update_own_task',
    'update_team_task',
    'view_own_profile',
    'update_own_profile',
    'view_team_profiles',
    'view_all_volunteers',
    'approve_volunteer',
    'promote_volunteer',
    'view_insights_own',
    'view_insights_team',
    'view_insights_ngo',
    'view_registry',
    'view_inventory',
    'request_inventory',
    'manage_inventory',
    'manage_ngo_settings',
  ],
  ngo_founder: [
    'view_home',
    'view_map',
    'view_tasks',
    'create_task',
    'create_need',
    'assign_task',
    'update_own_task',
    'update_team_task',
    'view_own_profile',
    'update_own_profile',
    'view_team_profiles',
    'view_all_volunteers',
    'approve_volunteer',
    'promote_volunteer',
    'view_insights_own',
    'view_insights_team',
    'view_insights_ngo',
    'view_registry',
    'manage_registry',
    'view_inventory',
    'request_inventory',
    'manage_inventory',
    'manage_ngo_settings',
  ],
  super_admin: [
    'view_home',
    'view_map',
    'view_tasks',
    'create_task',
    'create_need',
    'assign_task',
    'update_own_task',
    'update_team_task',
    'view_own_profile',
    'update_own_profile',
    'view_team_profiles',
    'view_all_volunteers',
    'approve_volunteer',
    'promote_volunteer',
    'view_insights_own',
    'view_insights_team',
    'view_insights_ngo',
    'view_registry',
    'manage_registry',
    'view_inventory',
    'request_inventory',
    'manage_inventory',
    'manage_ngo_settings',
    'manage_platform_settings',
  ],
};

export function getPermissionsForRole(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return getPermissionsForRole(role).includes(permission);
}
